### ISSUE TITLE
Add path to get more debug info from CheckObsreqTargetFromPcad 

### ISSUE THREAD

**Issue by jeanconn** [sot/hopper#4]
I had to hack a local copy of hopper to try find out that the problem was an incorrect detector used in the check for the first obsid of NOV16.   It might be good to have a regular path to getting more debugging info on that kind of thing (all of the parameters used in the check stuck into the check structure?).

**Comment by taldcroft** [comment]
Agreed that making introspection a bit easier would be good.

There isn't a programmatic way to know all the params used in a check.  In theory this could be a required class attribute, but I'd like to get more experience with the way things go wrong, and how we fix them, before going down that path.

**Comment by jeanconn** [comment]
For this one check, where the parameters were lightweight, and I didn't
really need stateful introspection,  my debug version just printed all the
parameters in the message.   Maybe just a flag for verbose messaging to do
that?   Or maybe the default warning message should just include detector
and both sets of coordinates?

**Comment by taldcroft** [comment]
In this particular case what would have prevented your confusion is a check that the OR detector matches the detector based on load SIMPOS.  That check will definitely be included, so in the future you would have immediately noted that the detector was not expected.  The goal is to keep checks as atomic as possible.

A debug mode which emits a representation of all state values for each check would be feasible.  

As far as I can tell printing "all the parameters in the message" can only be done by hand-coding per check what those parameters are (since they might not even be unique depending on the outcome).  I'm not too excited about that.

**Comment by jeanconn** [comment]
Hmm.  I still wonder if there would be value added in tracking which parameters a check accessed.  But I suppose this is still part of my confusion regarding your plan for implementation.  Are all of the inputs to the cmd checking going to be required all the time?  Or only if we've asked to do certain checks?   I would have liked this check to fail altogether when I ran hopper run_cmds with no initial state.

Some of my confusion in this case is, as you say, likely to be a non-issue when detector/simpos checks are in place.  As it was, it was not immediately clear to me that  "detector" in the check was using the sim-determined detector and not the or-requested detector.  And speaking of vocabulary, using "target_ra" and "target_dec" is a little tricky right around "targ_q_att" when they describe different "targets".  I saw you used a local variable to call targ_q_att "pcad", but I don't know if a new convention there would be a gift to our future selves.

**Comment by taldcroft** [comment]
Generally speaking checks will validate whether they have the required inputs and each check will decide how to handle missing dependencies.  That is the basic idea behind the `skip` output.  All this is quite likely to evolve, so I don't think we want to get too hung up on things.

As an overall philosophy, hopper will consider the spacecraft state defined by running loads to define the true value.  So that should be your default interpretation of things.  And considering the code says below, there isn't really any ambiquity:
```
            detector = SC.detector
```

Yes, `or_target_ra,dec` would be better.

**Comment by jeanconn** [comment]
>             detector = SC.detector

Though for an undercover, even that would be interesting.

**Comment by taldcroft** [comment]
> Though for an undercover, even that would be interesting.

What kind of issues might this cause for ACA checking or commanded states?

**Comment by jeanconn** [comment]
Not a problem unless 'detector' is used in a new way in checks on states
passed to thermal models.
